# Generated by Django 4.2.11 on 2026-08-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.BooleanField()),
                ('testo', models.CharField(max_length=200)),
            ],
        ),
    ]
